---

- name: Set hostname with bash
  shell: |
    sudo hostnamectl set-hostname SP19CLIENT.AD.SIU.EDU
  become: True
  args:
    executable: /bin/bash
  #delegate_to: localhost

- name: Configure /etc/hostname
  template:
    src: etc/hostname
    dest: /etc/hostname
    owner: root
    group: root
    mode: 0644
    backup: no



- name: Configure /etc/krb5.conf
  template:
    src: etc/krb5.conf
    dest: /etc/krb5.conf
    owner: root
    group: root
    mode: 0644
    backup: no


#- name: Configure /etc/sssd/sssd.conf
#  template:
#    src: etc/sssd/sssd.conf
#    dest: /etc/sssd/sssd.conf
#    owner: root
#    group: root
#    mode: 0644
#    backup: no


- name: Configure /etc/sysconfig/network
  template:
    src: etc/sysconfig/network
    dest: /etc/sysconfig/network
    owner: root
    group: root
    mode: 0644
    backup: no

