---

- name: upgrade all packages
  yum:
    name: '*'
    state: latest

# Install realmd_prereq_packages:
- name: install realmd_prereq_packages
  package: name={{ item }} state=present
  with_items: "{{ realmd_prereq_packages }}"

# Join AD
- include: ad.yml

